### ISSUE TITLE
PR Request: Revamp body writing

### ISSUE THREAD

**Issue by ninjrdevelop** [lewisKendall-Jones/azure-sdk-for-java-jdk8-httpurlconnection-client#118]
> This can just be return Mono.empty(). Though, I think these all should use the case for POST, PUT, and DELETE, I'm in the belief that the HttpClient shouldn't safe guard the request against invalid configuration as it could hide/mask incorrect behavior and it would be better for an exception to happen if a body gets sent with a HEAD request.

https://github.com/lewisKendall-Jones/azure-sdk-for-java-jdk8-httpurlconnection-client/blob/0dfd186a2a27d3a2d6608c97ad9a0d67730748aa/sdk/core/azure-core-http-httpurlconnection/src/main/java/com/azure/core/http/httpurlconnection/HttpUrlConnectionClient.java#L253

**Comment by ninjrdevelop** [comment]
We've tried to write body in all cases, but this causes an error with a single test (`validateHeadersReturnAsIs()`) - as the HTTP Method somehow becomes `POST` when the test server receives it.

**Comment by lewisKendall-Jones** [comment]
Reopened as we should be throwing an exception instead of returning Mono.empty()
