### ISSUE TITLE
Assertion Test Failure: HttpUrlConnectionAsyncClientTest : testConcurrentRequests()

### ISSUE THREAD

**Issue by lewisKendall-Jones** [lewisKendall-Jones/azure-sdk-for-java-jdk8-httpurlconnection-client#21]

**Comment by Jamelas** [comment]
Test passes after [this commit which merged the `main` branch and the `JoinClientWrapper` branch](https://github.com/lewisKendall-Jones/azure-sdk-for-java-jdk8-httpurlconnection-client/commit/bdcfc83526ae962dd4eb302af20daa76b7724881).

Solution: `HttpUrlConnectionClient` can now handle async operations
