### ISSUE TITLE
Exception Test Failure: HttpUrlConnectionAsyncClientTest : testFlowableWhenServerReturnsBodyAndNoErrorsWhenHttp500Returned()

### ISSUE THREAD

**Issue by lewisKendall-Jones** [lewisKendall-Jones/azure-sdk-for-java-jdk8-httpurlconnection-client#23]

**Comment by Jamelas** [comment]
Test passes after [this commit which merged the `main` branch and the `JoinClientWrapper` branch](https://github.com/lewisKendall-Jones/azure-sdk-for-java-jdk8-httpurlconnection-client/commit/bdcfc83526ae962dd4eb302af20daa76b7724881).

Solution: When calling the `HttpUrlConnectionClient.readResponse()` method, the connection will use `getErrorStream` if the response code is >= 400
