### ISSUE TITLE
Start implementing Microsoft's Unit tests

### ISSUE THREAD

**Issue by Jamelas** [lewisKendall-Jones/azure-sdk-for-java-jdk8-httpurlconnection-client#26]
Work with MS engineers to start implementing benchmark and unit tests.

Existing tests can be found here:
https://github.com/lewisKendall-Jones/azure-sdk-for-java-jdk8-httpurlconnection-client/tree/main/sdk/core/azure-core-test

**Comment by Jamelas** [comment]
As of 10/09/23, 332/531 tests are passing. This is up from the initial pass rate of 166/531.

Judging by the tests that are failing, it would be worth looking into how `Context` is handled in the `HttpUrlConnectionClient` and `HttpConnectionClientBuilder` classes

**Comment by lewisKendall-Jones** [comment]
Closing this as the Microsoft unit tests have been implemented. Test pass rates are more closely aligned with the 'Achieve 100% test success rate' milestone.
