### ISSUE TITLE
PR Review: Delete Demo Browser

### ISSUE THREAD

**Issue by Jamelas** [lewisKendall-Jones/azure-sdk-for-java-jdk8-httpurlconnection-client#28]
Delete the Demo Browser. 
The Demo Browser was for presentation purposes and will need to be deleted before merging the PR. **Before deleting**, it will be worth checking if it is needed for any of the remaining presentations.

File: [DemoBrowser.java](https://github.com/lewisKendall-Jones/azure-sdk-for-java-jdk8-httpurlconnection-client/blob/main/sdk/core/azure-core-http-httpurlconnection/src/main/java/com/azure/core/http/httpurlconnection/DemoBrowser.java)
Lines: All

[Comment from Jonathan](https://github.com/Azure/azure-sdk-for-java/pull/36626#discussion_r1314317375):
> This can eventually be deleted (before the PR is merged)

**Comment by lewisKendall-Jones** [comment]
Will delete immediately. If it's needed, we will grab it from the current commit
