### ISSUE TITLE
PR Review: Add JavaDoc to public API

### ISSUE THREAD

**Issue by Jamelas** [lewisKendall-Jones/azure-sdk-for-java-jdk8-httpurlconnection-client#29]
Add JavaDoc to all public API. 
Check existing clients for examples (e.g., [HttpClient](https://github.com/lewisKendall-Jones/azure-sdk-for-java-jdk8-httpurlconnection-client/tree/main/sdk/core/azure-core-http-jdk-httpclient/src/main/java/com/azure/core/http/jdk/httpclient), [Netty](https://github.com/lewisKendall-Jones/azure-sdk-for-java-jdk8-httpurlconnection-client/tree/main/sdk/core/azure-core-http-netty/src/main/java/com/azure/core/http/netty), etc.).

File: All public API
Lines: N/A

[Comment from Jonathan](https://github.com/Azure/azure-sdk-for-java/pull/36626#discussion_r1314317432):
> Be sure at some point to add JavaDoc to all public API

**Comment by ninjrdevelop** [comment]
Completed in c5ffbbd
