### ISSUE TITLE
PR Review: Updating the `sendPatchViaSocket` method

### ISSUE THREAD

**Issue by Jamelas** [lewisKendall-Jones/azure-sdk-for-java-jdk8-httpurlconnection-client#31]
Two requests from Jonathan for the `sendPatchViaSocket` method in the HttpUrlConnectionClient class.

- A new `SocketClient` is created for every request. Jonathan would like us to see if after a `SocketClient` is created, it can be reused (maybe through using a Singleton pattern?).
- Make sure the method is returning an `HttpResponse` from the `SocketClient`. Currently, it looks to be returning an empty `Mono`.

File: [HttpUrlConnectionClient](https://github.com/lewisKendall-Jones/azure-sdk-for-java-jdk8-httpurlconnection-client/blob/main/sdk/core/azure-core-http-httpurlconnection/src/main/java/com/azure/core/http/httpurlconnection/HttpUrlConnectionClient.java)
Line(s): 71-79

[Comment from Jonathan](https://github.com/Azure/azure-sdk-for-java/pull/36626#discussion_r1314318099):
> I might worry a little about the perf implications of newing up `SocketClient` instances for every request. It might be worth adding to your backlog an investigation on whether these should be reused in some way or not.

> Are you testing anywhere that the returned Mono contains an `HttpResponse` from the `SocketClient`? It looks like you are returning an empty `Mono`.

**Comment by Jamelas** [comment]
> Make sure the method is returning an `HttpResponse` from the `SocketClient`. Currently, it looks to be returning an empty `Mono`.

This part is completed.

**Comment by Jamelas** [comment]
> A new `SocketClient` is created for every request. Jonathan would like us to see if after a `SocketClient` is created, it can be reused (maybe through using a Singleton pattern?).

One possible solution is creating a `Map` to check for existing `SocketClient` objects before creating a new one. Before proceeding with this, it might be better to create some `SocketClient` tests so we know if any changes we make are effective or not.

**Comment by kdot-simmo** [comment]
I have partially resolved this issue by having sendPatchViaSocket return a Mono<HttpResponse>. I have also added an extra constructor to SocketClient to accept as URL as parameter. This constructor is used by sendPatchViaSocket.

**Comment by Jamelas** [comment]
Completed.

Added a `map` to keep track of existing `SocketClient` instances.
Check existing tests to confirm same pass rate and then merged to `main` branch with [this commit](https://github.com/lewisKendall-Jones/azure-sdk-for-java-jdk8-httpurlconnection-client/commit/ab069e353402c0ec3660edac38ef449ba37f77fe)
