### ISSUE TITLE
PR Review: Add switch statement to `writeRequestBody` method

### ISSUE THREAD

**Issue by Jamelas** [lewisKendall-Jones/azure-sdk-for-java-jdk8-httpurlconnection-client#33]
Add switch statement to replace the exising `||` (or) statement.
An example of what Jonathan wants can be found here: [`HttpUrlConnectionAsyncHttpClient.java` (lines 91-117)](https://github.com/Azure/azure-sdk-for-android/blob/main/sdk/core/azure-core-http-httpurlconnection/src/main/java/com/azure/android/core/http/httpurlconnection/HttpUrlConnectionAsyncHttpClient.java)

File: [HttpUrlConnectionClient](https://github.com/lewisKendall-Jones/azure-sdk-for-java-jdk8-httpurlconnection-client/blob/main/sdk/core/azure-core-http-httpurlconnection/src/main/java/com/azure/core/http/httpurlconnection/HttpUrlConnectionClient.java)
Lines: 103-124

[Comment from Jonathan](https://github.com/Azure/azure-sdk-for-java/pull/36626#discussion_r1314319128):
> From a style standpoing, I would rather we have an exhaustive switch statement here, e.g.
> 
> ```
> switch (httpRequest.getMethod()) {
>     case POST:
>     case PUT:
>     case PATCH: {
>         ...code
>     }
>     case <EVERYTHING ELSE>:
>     default: return Mono.empty();
> }
> ```

**Comment by lewisKendall-Jones** [comment]
Resolved in commit 550c273
