### ISSUE TITLE
PR Review: Move `HttpUrlConnectionResponse` to sub-package

### ISSUE THREAD

**Issue by Jamelas** [lewisKendall-Jones/azure-sdk-for-java-jdk8-httpurlconnection-client#36]
Move the `HttpUrlConnectionResponse` class to a sub-package named `implementation`. After moving, confirm that it can be accessed by classes currently using it (e.g., `HttpUrlConnectionClient`).

Examples of existing packages with sub-packages are [HttpClient](https://github.com/lewisKendall-Jones/azure-sdk-for-java-jdk8-httpurlconnection-client/tree/main/sdk/core/azure-core-http-jdk-httpclient/src/main/java/com/azure/core/http/jdk/httpclient) and [Netty](https://github.com/lewisKendall-Jones/azure-sdk-for-java-jdk8-httpurlconnection-client/tree/main/sdk/core/azure-core-http-netty/src/main/java/com/azure/core/http/netty)

File: [HttpUrlConnectionResponse](https://github.com/lewisKendall-Jones/azure-sdk-for-java-jdk8-httpurlconnection-client/blob/main/sdk/core/azure-core-http-httpurlconnection/src/main/java/com/azure/core/http/httpurlconnection/HttpUrlConnectionResponse.java)
Lines: N/A

[Comment from Jonathan](https://github.com/Azure/azure-sdk-for-java/pull/36626#discussion_r1314319833):
> This is not intended to be public API. Move custom response type into a sub-package named `implementation`, similar to the other http clients, or make the class 'package-private' so that it is not visible to classes outside this package.

**Comment by lewisKendall-Jones** [comment]
'implementation' created, now owning 'HttpUrlConnectionResponse'.
