### ISSUE TITLE
Report - Week 8

### ISSUE THREAD

**Issue by Jamelas** [lewisKendall-Jones/azure-sdk-for-java-jdk8-httpurlconnection-client#49]
Take ownership of the Week 8 Report.

Tasks include:

- Creation of Google Document
- Ensuring good progress is being made (i.e. it will be completed on time)
- Make sure the writing style used is consistent 
- Submit the completed report before the deadline

**Comment by lewisKendall-Jones** [comment]
Done and delivered.
