### ISSUE TITLE
Create a prototype client

### ISSUE THREAD

**Issue by Jamelas** [lewisKendall-Jones/azure-sdk-for-java-jdk8-httpurlconnection-client#52]
Create a client that uses the HttpUrlConnection class. 
Because it is an early prototype it is not yet expected to use PATCH methods or implement asynchronous communication.

This client will be expanded on in future sprints.

**Comment by ninjrdevelop** [comment]
This was completed for the Week 8 report. Not committed, as it'll just be removed again.
