### ISSUE TITLE
Fix the 'Provided Type' errors in HttpUrlConnectionClientTest

### ISSUE THREAD

**Issue by Jamelas** [lewisKendall-Jones/azure-sdk-for-java-jdk8-httpurlconnection-client#6]
[This can be linked from this issue.](https://github.com/lewisKendall-Jones/azure-sdk-for-java-jdk8-httpurlconnection-client/issues/1)

Changing the _send(HttpRequest)_ method in HttpUrlConnectionResponse has resulted in the provided type changing for some methods. The return type _may_ need to be converted to Mono type.

Errors are found on lines 33 and 42.

**Comment by lewisKendall-Jones** [comment]
This will be completed alongside issue #4 and will be closed in tandem.
