### ISSUE TITLE
PR Request: Remove blocking code from `HttpUrlConnectionClient`

### ISSUE THREAD

**Issue by Jamelas** [lewisKendall-Jones/azure-sdk-for-java-jdk8-httpurlconnection-client#76]
Request from Srikanta,
>Should not use blocking code in async method.

PR review comment can be found [here](https://github.com/Azure/azure-sdk-for-java/pull/36626#discussion_r1332083486).

**Comment by Jamelas** [comment]
`blockLast` is used in the code highlighted by Srikanta. This has since been replaced with `block` in [Issue #75](https://github.com/lewisKendall-Jones/azure-sdk-for-java-jdk8-httpurlconnection-client/issues/75#issuecomment-1732325076). I am not sure if this is an acceptable replacement as it is still blocking. Need to confirm

**Comment by ninjrdevelop** [comment]
Pending PR that's just been submitted.

**Comment by Jamelas** [comment]
Completing [this issue](https://github.com/users/lewisKendall-Jones/projects/4/views/2?pane=issue&itemId=40407493) first may result in `block` being removed.

**Comment by ninjrdevelop** [comment]
Have prodded Alan in Discord for some feedback on this, still don't have a great solution - even with the work being done in #83

**Comment by ninjrdevelop** [comment]
Still stuck on this. Dropping back to backlog for now.

**Comment by Jamelas** [comment]
Removed `block` from `sendAsync` and `sendRequest` methods.

Tests are passing as usual, merged to `main` branch.
