### ISSUE TITLE
PR Request: Add support  write, response, and read timeouts

### ISSUE THREAD

**Issue by Jamelas** [lewisKendall-Jones/azure-sdk-for-java-jdk8-httpurlconnection-client#81]
Request from Alan.

> Should work on adding support for write, response, and read timeouts as well. But this can be added later as it requires custom code unlike the `connect` timeout.

PR review can be found [here](https://github.com/Azure/azure-sdk-for-java/pull/36626#discussion_r1343210103).

<strike>
_Additionally, this looks like it is always used as `connectionTimeout.toMillis()`, since `Duration` is immutable we should just eagerly convert this to millis in the constructor. And use `-1` as the representation of "no connection timeout"
</strike>

(implemented in c64b40b)

**Comment by lewisKendall-Jones** [comment]
Connect, write, response, and read timeouts implemented as of 8c4761f336605dfb3c5e8dc071c6f8f7421af8a9
