### ISSUE TITLE
PR Request: Create seperate synchronous and asynchronous APIs

### ISSUE THREAD

**Issue by Jamelas** [lewisKendall-Jones/azure-sdk-for-java-jdk8-httpurlconnection-client#82]
PR request from Alan:
> Since `HttpURLConnection` is inherently synchronous we should create a separate implementation for this API instead of blocking the asynchronous API. But to help code reuse we can create helper methods that can be shared across both the asynchronous and synchronous API.

PR review can be found [here](https://github.com/Azure/azure-sdk-for-java/pull/36626#discussion_r1343211068).

**Comment by ninjrdevelop** [comment]
Partial completion by 34a278a? Have got `sendSync` no longer just being `sendAsync().block()`.
I'm asking for further clarity from Alan here: https://github.com/Azure/azure-sdk-for-java/pull/36626#discussion_r1346934548

**Comment by lewisKendall-Jones** [comment]
https://github.com/Azure/azure-sdk-for-java/pull/36626#discussion_r1347603010

Confirmed that we're not needing to make another class. [34a278a ](https://github.com/lewisKendall-Jones/azure-sdk-for-java-jdk8-httpurlconnection-client/commit/34a278a4d5b3aafe315fde780c7abdefb2676cd3) has solved this issue.

**Comment by lewisKendall-Jones** [comment]
Reopening as the branch wasn't merged in time. The content of sendRequest() has now changed to a point where this branch cannot be safely merged.
