### ISSUE TITLE
PR Request: Divide and seperate logic in `handleConnection` method.

### ISSUE THREAD

**Issue by Jamelas** [lewisKendall-Jones/azure-sdk-for-java-jdk8-httpurlconnection-client#83]
PR request from Alan:

> Let's break this method down into smaller chunks of logic, my initial thought on the split is
> 
>     * connect
> 
>     * sendRequest
> 
>     * receiveResponse

PR review can be found [here](https://github.com/Azure/azure-sdk-for-java/pull/36626#discussion_r1343211811).

**Note:** If chaining methods result in `block` being removed, [this issue](https://github.com/users/lewisKendall-Jones/projects/4?pane=issue&itemId=39575188) can be marked as complete.

**Comment by ninjrdevelop** [comment]
Closed by 411e1a1
