### ISSUE TITLE
PR Request: Add support for `Digest` authentication

### ISSUE THREAD

**Issue by Jamelas** [lewisKendall-Jones/azure-sdk-for-java-jdk8-httpurlconnection-client#84]
PR request from Alan:
> `Digest` authentication needs support as well.

PR review can be found [here](https://github.com/Azure/azure-sdk-for-java/pull/36626#discussion_r1343212426).

**Comment by JAnders01** [comment]
Added digest authentication, unsure of what messagedigest algorithm to use (MD5, SHA-1, SHA-256) to use.

**Comment by lewisKendall-Jones** [comment]
Almost done, just need to add a way to select basic or digest authentication.

**Comment by lewisKendall-Jones** [comment]
An implementation has been made, but tests need to be made for digest.
