### ISSUE TITLE
PR Request: Swap `Flux<ByteBuffer> for `BinaryData`

### ISSUE THREAD

**Issue by Jamelas** [lewisKendall-Jones/azure-sdk-for-java-jdk8-httpurlconnection-client#86]
PR request from Alan:
> I think it would be better to work with `BinaryData` here than `Flux<ByteBuffer>` as `getBody` will convert non-`Flux<ByteBuffer>` request bodies to `Flux<ByteBuffer>` which could introduce a lot of overhead.
> 
> That said, I think this is something that can be deferred until later on once the initial implementation and testing are complete.

PR review can be found [here](https://github.com/Azure/azure-sdk-for-java/pull/36626#discussion_r1343214418).

**Comment by lewisKendall-Jones** [comment]
https://github.com/lewisKendall-Jones/azure-sdk-for-java-jdk8-httpurlconnection-client/commit/51e9c0529df5484c80442ab41f7bf4bc94efda65
