### ISSUE TITLE
PR Request: Consider using `HTTP/1.1` in `SocketClient`

### ISSUE THREAD

**Issue by Jamelas** [lewisKendall-Jones/azure-sdk-for-java-jdk8-httpurlconnection-client#88]
PR request from Alan:
> Should this be using `HTTP/1.0` or `HTTP/1.1`?

PR review can be found [here](https://github.com/Azure/azure-sdk-for-java/pull/36626#discussion_r1343217288).

**Note**: Only changing the `HTTP_VERSION` from `HTTP/1.0` to `HTTP/1.1` drastically increases the time needed to complete the test class (specifically `syncPatachRequest` and  `asyncPatchRequest`).

**Comment by Jamelas** [comment]
PR request from Alan:
> Should this be using `HTTP/1.0` or `HTTP/1.1`?

PR review can be found [here](https://github.com/Azure/azure-sdk-for-java/pull/36626#discussion_r1343217288).


**Note**: Only changing the `HTTP_VERSION` from `HTTP/1.0` to `HTTP/1.1` drastically increases the time needed to complete the test class (specifically `syncPatachRequest` and  `asyncPatchRequest`).

**Comment by kdot-simmo** [comment]
Changed back to HTTP/1.1. Added a check for connection header. If it hasn't been set to 'keep-alive', set it to 'close'
