### ISSUE TITLE
PR Request: Re-evaluate use of `\n` in the reponse body for `SocketClient`

### ISSUE THREAD

**Issue by Jamelas** [lewisKendall-Jones/azure-sdk-for-java-jdk8-httpurlconnection-client#91]
PR request from Alan:
> Could this introduce a bug where there is an additional trailing `\n` in the response body? Also, isn't there a newline between the headers and response body?

PR review can be found [here](https://github.com/Azure/azure-sdk-for-java/pull/36626#discussion_r1343220905).

**Comment by kdot-simmo** [comment]
Removed newline from response body. Unsure about comment about newline between the headers and body, it should be read through by the preceding while loop.
