### ISSUE TITLE
PR Request: Change the `buildPatchRequest` in `SocketClient` to `void`

### ISSUE THREAD

**Issue by Jamelas** [lewisKendall-Jones/azure-sdk-for-java-jdk8-httpurlconnection-client#92]
PR request from Alan:
> I think this API would be better off being `void` and taking the stream sending the request. That way it can write the patch request directly to the network instead of buffering it once before sending it.

PR review can be found [here](https://github.com/Azure/azure-sdk-for-java/pull/36626#discussion_r1343221982).

**Comment by kdot-simmo** [comment]
buildPatchRequest changed to void. Now takes the output stream as a parameter and sends the request directly. Method renamed to buildAndSend.
