### ISSUE TITLE
PR Request: Change output for multi-value headers in `SocketClient`

### ISSUE THREAD

**Issue by Jamelas** [lewisKendall-Jones/azure-sdk-for-java-jdk8-httpurlconnection-client#93]
PR request from Alan:
> Should multi-value headers be sent as
> 
> ```
> headername: headervalue1,headervalue2
> ```
> 
> or
> 
> ```
> headername: headervalue1
> headername: headervalue2
> ```
> 
> ?
> 
> Right, now this is doing the first case.

PR review can be found [here](https://github.com/Azure/azure-sdk-for-java/pull/36626#discussion_r1343222778).

**Note**: the constructor for `HttpUrlConnectionResponse` handles headers with multiple values. It might be worth checking if the same can be implemented in `SocketClient`.

**Comment by ninjrdevelop** [comment]
Note: OkHttp does it the latter way:

sdk/core/azure-core-http-okhttp/src/main/java/com/azure/core/http/okhttp/OkHttpAsyncHttpClient.java#L134-L138

![image](https://github.com/lewisKendall-Jones/azure-sdk-for-java-jdk8-httpurlconnection-client/assets/72955871/17b3a56d-1b03-47e0-b043-cae92db9732f)

**Comment by kdot-simmo** [comment]
buildPatchRequest() changed to allow for multi-value headers similar to the OkHttp example. Thanks Craig
