### ISSUE TITLE
PR Request: Prevent non-blocking threads in client class

### ISSUE THREAD

**Issue by Jamelas** [lewisKendall-Jones/azure-sdk-for-java-jdk8-httpurlconnection-client#94]
PR request from Alan:
> Since this API is writing to blocking streams and reading from blocking streams, this should be `publishOn(Schedulers.boundedElastic())` to prevent blocking non-blocking threads.

PR review can be found [here](https://github.com/Azure/azure-sdk-for-java/pull/36626#discussion_r1343223683).

**Comment by ninjrdevelop** [comment]
Closed by 411e1a1
